import { render } from '@testing-library/react'
import { metadata } from '../layout'  // Import metadata directly

// Mock the Geist font
jest.mock('geist/font', () => ({
  GeistSans: {
    className: 'test-font-class'
  }
}))

// Create a mock component to test layout functionality
const MockLayout = ({ children }) => {
  return <div data-testid="mock-layout">{children}</div>
}

// Mock the actual layout to avoid html/body rendering issues
jest.mock('../layout', () => ({
  __esModule: true,
  default: function RootLayout({ children }) {
    return <MockLayout>{children}</MockLayout>
  },
  metadata: {
    title: "edukado",
    description: "Generated by create next app",
  }
}))

describe('RootLayout', () => {
  it('renders children correctly', () => {
    const { getByTestId } = render(
      <MockLayout>
        <div data-testid="test-child">Test Content</div>
      </MockLayout>
    )

    const layout = getByTestId('mock-layout')
    const child = getByTestId('test-child')
    
    expect(layout).toBeInTheDocument()
    expect(child).toBeInTheDocument()
    expect(child).toHaveTextContent('Test Content')
  })

  it('has correct metadata', () => {
    expect(metadata).toEqual({
      title: "edukado",
      description: "Generated by create next app",
    })
  })
})
