import './globals.css'
import { Metadata } from 'next'
import { GeistSans } from 'geist/font/sans'
import { Toaster } from "sonner";

// Keep metadata at the top level
export const metadata: Metadata = {
  title: "edukado",
  description: "Generated by create next app",
};

// Move this to a new ThemeRegistry component
const fontClass = GeistSans.className;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={fontClass}>
      <body className="min-h-screen bg-black">
        {children}
        <Toaster />
      </body>
    </html>
  );
}
