import type { Metadata } from "next";
import { GeistSans } from 'geist/font'
import "./globals.css";

// Move font class outside component to ensure consistent value
const fontClass = GeistSans.className

export const metadata: Metadata = {
  title: "edukado",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={fontClass}>
      <body suppressHydrationWarning={true}>{children}</body>
    </html>
  )
}
